/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as BlogSitemapDotxmlRouteImport } from './routes/blog-sitemap[.]xml'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as QuizQuizSlugRouteImport } from './routes/quiz/$quizSlug'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'
import { Route as AuthReadyRouteImport } from './routes/auth/ready'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as publicVideoWallCinematicRouteImport } from './routes/(public)/video-wall-cinematic'
import { Route as publicVideoWallRouteImport } from './routes/(public)/video-wall'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as UserAuthenticatedRouteRouteImport } from './routes/user/_authenticated/route'
import { Route as MeAuthenticatedRouteRouteImport } from './routes/me/_authenticated/route'
import { Route as AdminAuthenticatedRouteRouteImport } from './routes/admin/_authenticated/route'
import { Route as UserAuthenticatedIndexRouteImport } from './routes/user/_authenticated/index'
import { Route as MeAuthenticatedIndexRouteImport } from './routes/me/_authenticated/index'
import { Route as DocsUxGuidelinesIndexRouteImport } from './routes/docs/ux-guidelines/index'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin/_authenticated/index'
import { Route as DocsUxGuidelinesOverlaysRouteImport } from './routes/docs/ux-guidelines/overlays'
import { Route as DocsUxGuidelinesNavigationRouteImport } from './routes/docs/ux-guidelines/navigation'
import { Route as DocsUxGuidelinesLayoutFlowsRouteImport } from './routes/docs/ux-guidelines/layout-flows'
import { Route as DocsUxGuidelinesFormsRouteImport } from './routes/docs/ux-guidelines/forms'
import { Route as DocsUxGuidelinesFeedbackRouteImport } from './routes/docs/ux-guidelines/feedback'
import { Route as DocsUxGuidelinesAccessibilityRouteImport } from './routes/docs/ux-guidelines/accessibility'
import { Route as publicLegalTermsRouteImport } from './routes/(public)/legal/terms'
import { Route as publicLegalPrivacyRouteImport } from './routes/(public)/legal/privacy'
import { Route as publicLegalCookiesRouteImport } from './routes/(public)/legal/cookies'
import { Route as AdminAuthenticatedBlogsRouteRouteImport } from './routes/admin/_authenticated/blogs/route'
import { Route as MeAuthenticatedProfileIndexRouteImport } from './routes/me/_authenticated/profile/index'
import { Route as MeAuthenticatedNotificationsIndexRouteImport } from './routes/me/_authenticated/notifications/index'
import { Route as MeAuthenticatedAppearanceIndexRouteImport } from './routes/me/_authenticated/appearance/index'
import { Route as MeAuthenticatedAccountIndexRouteImport } from './routes/me/_authenticated/account/index'
import { Route as AdminAuthenticatedUsersIndexRouteImport } from './routes/admin/_authenticated/users/index'
import { Route as AdminAuthenticatedTasksIndexRouteImport } from './routes/admin/_authenticated/tasks/index'
import { Route as AdminAuthenticatedQuizAnalyticsIndexRouteImport } from './routes/admin/_authenticated/quiz-analytics/index'
import { Route as AdminAuthenticatedKanbanIndexRouteImport } from './routes/admin/_authenticated/kanban/index'
import { Route as AdminAuthenticatedHelpCenterIndexRouteImport } from './routes/admin/_authenticated/help-center/index'
import { Route as AdminAuthenticatedChatsIndexRouteImport } from './routes/admin/_authenticated/chats/index'
import { Route as AdminAuthenticatedCalendarIndexRouteImport } from './routes/admin/_authenticated/calendar/index'
import { Route as AdminAuthenticatedBlogsIndexRouteImport } from './routes/admin/_authenticated/blogs/index'
import { Route as AdminAuthenticatedAppsIndexRouteImport } from './routes/admin/_authenticated/apps/index'
import { Route as AdminAuthenticatedBlogsNewRouteImport } from './routes/admin/_authenticated/blogs/new'
import { Route as AdminAuthenticatedBlogsIdEditRouteImport } from './routes/admin/_authenticated/blogs/$id.edit'

const UserRouteImport = createFileRoute('/user')()
const MeRouteImport = createFileRoute('/me')()
const AdminRouteImport = createFileRoute('/admin')()
const DesignSystemBadgesLazyRouteImport = createFileRoute(
  '/design-system/badges',
)()
const AdminAuthenticatedQuizManagementLazyRouteImport = createFileRoute(
  '/admin/_authenticated/quiz-management',
)()
const AdminAuthenticatedDemosThreePaneNavigatorLazyRouteImport =
  createFileRoute('/admin/_authenticated/demos/three-pane-navigator')()

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSitemapDotxmlRoute = BlogSitemapDotxmlRouteImport.update({
  id: '/blog-sitemap.xml',
  path: '/blog-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemBadgesLazyRoute = DesignSystemBadgesLazyRouteImport.update({
  id: '/design-system/badges',
  path: '/design-system/badges',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/design-system/badges.lazy').then((d) => d.Route),
)
const QuizQuizSlugRoute = QuizQuizSlugRouteImport.update({
  id: '/quiz/$quizSlug',
  path: '/quiz/$quizSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthReadyRoute = AuthReadyRouteImport.update({
  id: '/auth/ready',
  path: '/auth/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const publicVideoWallCinematicRoute =
  publicVideoWallCinematicRouteImport.update({
    id: '/(public)/video-wall-cinematic',
    path: '/video-wall-cinematic',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicVideoWallRoute = publicVideoWallRouteImport.update({
  id: '/(public)/video-wall',
  path: '/video-wall',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAuthenticatedRouteRoute = UserAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => UserRoute,
} as any)
const MeAuthenticatedRouteRoute = MeAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => MeRoute,
} as any)
const AdminAuthenticatedRouteRoute = AdminAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminRoute,
} as any)
const UserAuthenticatedIndexRoute = UserAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserAuthenticatedRouteRoute,
} as any)
const MeAuthenticatedIndexRoute = MeAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeAuthenticatedRouteRoute,
} as any)
const DocsUxGuidelinesIndexRoute = DocsUxGuidelinesIndexRouteImport.update({
  id: '/ux-guidelines/',
  path: '/ux-guidelines/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRouteRoute,
} as any)
const AdminAuthenticatedQuizManagementLazyRoute =
  AdminAuthenticatedQuizManagementLazyRouteImport.update({
    id: '/quiz-management',
    path: '/quiz-management',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/admin/_authenticated/quiz-management.lazy').then(
      (d) => d.Route,
    ),
  )
const DocsUxGuidelinesOverlaysRoute =
  DocsUxGuidelinesOverlaysRouteImport.update({
    id: '/ux-guidelines/overlays',
    path: '/ux-guidelines/overlays',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsUxGuidelinesNavigationRoute =
  DocsUxGuidelinesNavigationRouteImport.update({
    id: '/ux-guidelines/navigation',
    path: '/ux-guidelines/navigation',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsUxGuidelinesLayoutFlowsRoute =
  DocsUxGuidelinesLayoutFlowsRouteImport.update({
    id: '/ux-guidelines/layout-flows',
    path: '/ux-guidelines/layout-flows',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsUxGuidelinesFormsRoute = DocsUxGuidelinesFormsRouteImport.update({
  id: '/ux-guidelines/forms',
  path: '/ux-guidelines/forms',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsUxGuidelinesFeedbackRoute =
  DocsUxGuidelinesFeedbackRouteImport.update({
    id: '/ux-guidelines/feedback',
    path: '/ux-guidelines/feedback',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsUxGuidelinesAccessibilityRoute =
  DocsUxGuidelinesAccessibilityRouteImport.update({
    id: '/ux-guidelines/accessibility',
    path: '/ux-guidelines/accessibility',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const publicLegalTermsRoute = publicLegalTermsRouteImport.update({
  id: '/(public)/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLegalPrivacyRoute = publicLegalPrivacyRouteImport.update({
  id: '/(public)/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLegalCookiesRoute = publicLegalCookiesRouteImport.update({
  id: '/(public)/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedBlogsRouteRoute =
  AdminAuthenticatedBlogsRouteRouteImport.update({
    id: '/blogs',
    path: '/blogs',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const MeAuthenticatedProfileIndexRoute =
  MeAuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => MeAuthenticatedRouteRoute,
  } as any)
const MeAuthenticatedNotificationsIndexRoute =
  MeAuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => MeAuthenticatedRouteRoute,
  } as any)
const MeAuthenticatedAppearanceIndexRoute =
  MeAuthenticatedAppearanceIndexRouteImport.update({
    id: '/appearance/',
    path: '/appearance/',
    getParentRoute: () => MeAuthenticatedRouteRoute,
  } as any)
const MeAuthenticatedAccountIndexRoute =
  MeAuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => MeAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedUsersIndexRoute =
  AdminAuthenticatedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedTasksIndexRoute =
  AdminAuthenticatedTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedQuizAnalyticsIndexRoute =
  AdminAuthenticatedQuizAnalyticsIndexRouteImport.update({
    id: '/quiz-analytics/',
    path: '/quiz-analytics/',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedKanbanIndexRoute =
  AdminAuthenticatedKanbanIndexRouteImport.update({
    id: '/kanban/',
    path: '/kanban/',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedHelpCenterIndexRoute =
  AdminAuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedChatsIndexRoute =
  AdminAuthenticatedChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedCalendarIndexRoute =
  AdminAuthenticatedCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedBlogsIndexRoute =
  AdminAuthenticatedBlogsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAuthenticatedBlogsRouteRoute,
  } as any)
const AdminAuthenticatedAppsIndexRoute =
  AdminAuthenticatedAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedDemosThreePaneNavigatorLazyRoute =
  AdminAuthenticatedDemosThreePaneNavigatorLazyRouteImport.update({
    id: '/demos/three-pane-navigator',
    path: '/demos/three-pane-navigator',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/admin/_authenticated/demos/three-pane-navigator.lazy'
    ).then((d) => d.Route),
  )
const AdminAuthenticatedBlogsNewRoute =
  AdminAuthenticatedBlogsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAuthenticatedBlogsRouteRoute,
  } as any)
const AdminAuthenticatedBlogsIdEditRoute =
  AdminAuthenticatedBlogsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AdminAuthenticatedBlogsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/docs': typeof DocsRouteRouteWithChildren
  '/blog-sitemap.xml': typeof BlogSitemapDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminAuthenticatedRouteRouteWithChildren
  '/me': typeof MeAuthenticatedRouteRouteWithChildren
  '/user': typeof UserAuthenticatedRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/video-wall': typeof publicVideoWallRoute
  '/video-wall-cinematic': typeof publicVideoWallCinematicRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/ready': typeof AuthReadyRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/quiz/$quizSlug': typeof QuizQuizSlugRoute
  '/design-system/badges': typeof DesignSystemBadgesLazyRoute
  '/': typeof publicIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/admin/blogs': typeof AdminAuthenticatedBlogsRouteRouteWithChildren
  '/legal/cookies': typeof publicLegalCookiesRoute
  '/legal/privacy': typeof publicLegalPrivacyRoute
  '/legal/terms': typeof publicLegalTermsRoute
  '/docs/ux-guidelines/accessibility': typeof DocsUxGuidelinesAccessibilityRoute
  '/docs/ux-guidelines/feedback': typeof DocsUxGuidelinesFeedbackRoute
  '/docs/ux-guidelines/forms': typeof DocsUxGuidelinesFormsRoute
  '/docs/ux-guidelines/layout-flows': typeof DocsUxGuidelinesLayoutFlowsRoute
  '/docs/ux-guidelines/navigation': typeof DocsUxGuidelinesNavigationRoute
  '/docs/ux-guidelines/overlays': typeof DocsUxGuidelinesOverlaysRoute
  '/admin/quiz-management': typeof AdminAuthenticatedQuizManagementLazyRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
  '/docs/ux-guidelines': typeof DocsUxGuidelinesIndexRoute
  '/me/': typeof MeAuthenticatedIndexRoute
  '/user/': typeof UserAuthenticatedIndexRoute
  '/admin/blogs/new': typeof AdminAuthenticatedBlogsNewRoute
  '/admin/demos/three-pane-navigator': typeof AdminAuthenticatedDemosThreePaneNavigatorLazyRoute
  '/admin/apps': typeof AdminAuthenticatedAppsIndexRoute
  '/admin/blogs/': typeof AdminAuthenticatedBlogsIndexRoute
  '/admin/calendar': typeof AdminAuthenticatedCalendarIndexRoute
  '/admin/chats': typeof AdminAuthenticatedChatsIndexRoute
  '/admin/help-center': typeof AdminAuthenticatedHelpCenterIndexRoute
  '/admin/kanban': typeof AdminAuthenticatedKanbanIndexRoute
  '/admin/quiz-analytics': typeof AdminAuthenticatedQuizAnalyticsIndexRoute
  '/admin/tasks': typeof AdminAuthenticatedTasksIndexRoute
  '/admin/users': typeof AdminAuthenticatedUsersIndexRoute
  '/me/account': typeof MeAuthenticatedAccountIndexRoute
  '/me/appearance': typeof MeAuthenticatedAppearanceIndexRoute
  '/me/notifications': typeof MeAuthenticatedNotificationsIndexRoute
  '/me/profile': typeof MeAuthenticatedProfileIndexRoute
  '/admin/blogs/$id/edit': typeof AdminAuthenticatedBlogsIdEditRoute
}
export interface FileRoutesByTo {
  '/docs': typeof DocsRouteRouteWithChildren
  '/blog-sitemap.xml': typeof BlogSitemapDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/me': typeof MeAuthenticatedIndexRoute
  '/user': typeof UserAuthenticatedIndexRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/video-wall': typeof publicVideoWallRoute
  '/video-wall-cinematic': typeof publicVideoWallCinematicRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/ready': typeof AuthReadyRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/quiz/$quizSlug': typeof QuizQuizSlugRoute
  '/design-system/badges': typeof DesignSystemBadgesLazyRoute
  '/': typeof publicIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/legal/cookies': typeof publicLegalCookiesRoute
  '/legal/privacy': typeof publicLegalPrivacyRoute
  '/legal/terms': typeof publicLegalTermsRoute
  '/docs/ux-guidelines/accessibility': typeof DocsUxGuidelinesAccessibilityRoute
  '/docs/ux-guidelines/feedback': typeof DocsUxGuidelinesFeedbackRoute
  '/docs/ux-guidelines/forms': typeof DocsUxGuidelinesFormsRoute
  '/docs/ux-guidelines/layout-flows': typeof DocsUxGuidelinesLayoutFlowsRoute
  '/docs/ux-guidelines/navigation': typeof DocsUxGuidelinesNavigationRoute
  '/docs/ux-guidelines/overlays': typeof DocsUxGuidelinesOverlaysRoute
  '/admin/quiz-management': typeof AdminAuthenticatedQuizManagementLazyRoute
  '/docs/ux-guidelines': typeof DocsUxGuidelinesIndexRoute
  '/admin/blogs/new': typeof AdminAuthenticatedBlogsNewRoute
  '/admin/demos/three-pane-navigator': typeof AdminAuthenticatedDemosThreePaneNavigatorLazyRoute
  '/admin/apps': typeof AdminAuthenticatedAppsIndexRoute
  '/admin/blogs': typeof AdminAuthenticatedBlogsIndexRoute
  '/admin/calendar': typeof AdminAuthenticatedCalendarIndexRoute
  '/admin/chats': typeof AdminAuthenticatedChatsIndexRoute
  '/admin/help-center': typeof AdminAuthenticatedHelpCenterIndexRoute
  '/admin/kanban': typeof AdminAuthenticatedKanbanIndexRoute
  '/admin/quiz-analytics': typeof AdminAuthenticatedQuizAnalyticsIndexRoute
  '/admin/tasks': typeof AdminAuthenticatedTasksIndexRoute
  '/admin/users': typeof AdminAuthenticatedUsersIndexRoute
  '/me/account': typeof MeAuthenticatedAccountIndexRoute
  '/me/appearance': typeof MeAuthenticatedAppearanceIndexRoute
  '/me/notifications': typeof MeAuthenticatedNotificationsIndexRoute
  '/me/profile': typeof MeAuthenticatedProfileIndexRoute
  '/admin/blogs/$id/edit': typeof AdminAuthenticatedBlogsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/docs': typeof DocsRouteRouteWithChildren
  '/blog-sitemap.xml': typeof BlogSitemapDotxmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_authenticated': typeof AdminAuthenticatedRouteRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/me/_authenticated': typeof MeAuthenticatedRouteRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/user/_authenticated': typeof UserAuthenticatedRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(public)/video-wall': typeof publicVideoWallRoute
  '/(public)/video-wall-cinematic': typeof publicVideoWallCinematicRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/ready': typeof AuthReadyRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/quiz/$quizSlug': typeof QuizQuizSlugRoute
  '/design-system/badges': typeof DesignSystemBadgesLazyRoute
  '/(public)/': typeof publicIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/admin/_authenticated/blogs': typeof AdminAuthenticatedBlogsRouteRouteWithChildren
  '/(public)/legal/cookies': typeof publicLegalCookiesRoute
  '/(public)/legal/privacy': typeof publicLegalPrivacyRoute
  '/(public)/legal/terms': typeof publicLegalTermsRoute
  '/docs/ux-guidelines/accessibility': typeof DocsUxGuidelinesAccessibilityRoute
  '/docs/ux-guidelines/feedback': typeof DocsUxGuidelinesFeedbackRoute
  '/docs/ux-guidelines/forms': typeof DocsUxGuidelinesFormsRoute
  '/docs/ux-guidelines/layout-flows': typeof DocsUxGuidelinesLayoutFlowsRoute
  '/docs/ux-guidelines/navigation': typeof DocsUxGuidelinesNavigationRoute
  '/docs/ux-guidelines/overlays': typeof DocsUxGuidelinesOverlaysRoute
  '/admin/_authenticated/quiz-management': typeof AdminAuthenticatedQuizManagementLazyRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
  '/docs/ux-guidelines/': typeof DocsUxGuidelinesIndexRoute
  '/me/_authenticated/': typeof MeAuthenticatedIndexRoute
  '/user/_authenticated/': typeof UserAuthenticatedIndexRoute
  '/admin/_authenticated/blogs/new': typeof AdminAuthenticatedBlogsNewRoute
  '/admin/_authenticated/demos/three-pane-navigator': typeof AdminAuthenticatedDemosThreePaneNavigatorLazyRoute
  '/admin/_authenticated/apps/': typeof AdminAuthenticatedAppsIndexRoute
  '/admin/_authenticated/blogs/': typeof AdminAuthenticatedBlogsIndexRoute
  '/admin/_authenticated/calendar/': typeof AdminAuthenticatedCalendarIndexRoute
  '/admin/_authenticated/chats/': typeof AdminAuthenticatedChatsIndexRoute
  '/admin/_authenticated/help-center/': typeof AdminAuthenticatedHelpCenterIndexRoute
  '/admin/_authenticated/kanban/': typeof AdminAuthenticatedKanbanIndexRoute
  '/admin/_authenticated/quiz-analytics/': typeof AdminAuthenticatedQuizAnalyticsIndexRoute
  '/admin/_authenticated/tasks/': typeof AdminAuthenticatedTasksIndexRoute
  '/admin/_authenticated/users/': typeof AdminAuthenticatedUsersIndexRoute
  '/me/_authenticated/account/': typeof MeAuthenticatedAccountIndexRoute
  '/me/_authenticated/appearance/': typeof MeAuthenticatedAppearanceIndexRoute
  '/me/_authenticated/notifications/': typeof MeAuthenticatedNotificationsIndexRoute
  '/me/_authenticated/profile/': typeof MeAuthenticatedProfileIndexRoute
  '/admin/_authenticated/blogs/$id/edit': typeof AdminAuthenticatedBlogsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/docs'
    | '/blog-sitemap.xml'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/me'
    | '/user'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/video-wall'
    | '/video-wall-cinematic'
    | '/auth/callback'
    | '/auth/ready'
    | '/blogs/$slug'
    | '/quiz/$quizSlug'
    | '/design-system/badges'
    | '/'
    | '/blogs'
    | '/admin/blogs'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/docs/ux-guidelines/accessibility'
    | '/docs/ux-guidelines/feedback'
    | '/docs/ux-guidelines/forms'
    | '/docs/ux-guidelines/layout-flows'
    | '/docs/ux-guidelines/navigation'
    | '/docs/ux-guidelines/overlays'
    | '/admin/quiz-management'
    | '/admin/'
    | '/docs/ux-guidelines'
    | '/me/'
    | '/user/'
    | '/admin/blogs/new'
    | '/admin/demos/three-pane-navigator'
    | '/admin/apps'
    | '/admin/blogs/'
    | '/admin/calendar'
    | '/admin/chats'
    | '/admin/help-center'
    | '/admin/kanban'
    | '/admin/quiz-analytics'
    | '/admin/tasks'
    | '/admin/users'
    | '/me/account'
    | '/me/appearance'
    | '/me/notifications'
    | '/me/profile'
    | '/admin/blogs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/docs'
    | '/blog-sitemap.xml'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/me'
    | '/user'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/video-wall'
    | '/video-wall-cinematic'
    | '/auth/callback'
    | '/auth/ready'
    | '/blogs/$slug'
    | '/quiz/$quizSlug'
    | '/design-system/badges'
    | '/'
    | '/blogs'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/docs/ux-guidelines/accessibility'
    | '/docs/ux-guidelines/feedback'
    | '/docs/ux-guidelines/forms'
    | '/docs/ux-guidelines/layout-flows'
    | '/docs/ux-guidelines/navigation'
    | '/docs/ux-guidelines/overlays'
    | '/admin/quiz-management'
    | '/docs/ux-guidelines'
    | '/admin/blogs/new'
    | '/admin/demos/three-pane-navigator'
    | '/admin/apps'
    | '/admin/blogs'
    | '/admin/calendar'
    | '/admin/chats'
    | '/admin/help-center'
    | '/admin/kanban'
    | '/admin/quiz-analytics'
    | '/admin/tasks'
    | '/admin/users'
    | '/me/account'
    | '/me/appearance'
    | '/me/notifications'
    | '/me/profile'
    | '/admin/blogs/$id/edit'
  id:
    | '__root__'
    | '/docs'
    | '/blog-sitemap.xml'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/_authenticated'
    | '/me'
    | '/me/_authenticated'
    | '/user'
    | '/user/_authenticated'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(public)/video-wall'
    | '/(public)/video-wall-cinematic'
    | '/auth/callback'
    | '/auth/ready'
    | '/blogs/$slug'
    | '/quiz/$quizSlug'
    | '/design-system/badges'
    | '/(public)/'
    | '/blogs/'
    | '/admin/_authenticated/blogs'
    | '/(public)/legal/cookies'
    | '/(public)/legal/privacy'
    | '/(public)/legal/terms'
    | '/docs/ux-guidelines/accessibility'
    | '/docs/ux-guidelines/feedback'
    | '/docs/ux-guidelines/forms'
    | '/docs/ux-guidelines/layout-flows'
    | '/docs/ux-guidelines/navigation'
    | '/docs/ux-guidelines/overlays'
    | '/admin/_authenticated/quiz-management'
    | '/admin/_authenticated/'
    | '/docs/ux-guidelines/'
    | '/me/_authenticated/'
    | '/user/_authenticated/'
    | '/admin/_authenticated/blogs/new'
    | '/admin/_authenticated/demos/three-pane-navigator'
    | '/admin/_authenticated/apps/'
    | '/admin/_authenticated/blogs/'
    | '/admin/_authenticated/calendar/'
    | '/admin/_authenticated/chats/'
    | '/admin/_authenticated/help-center/'
    | '/admin/_authenticated/kanban/'
    | '/admin/_authenticated/quiz-analytics/'
    | '/admin/_authenticated/tasks/'
    | '/admin/_authenticated/users/'
    | '/me/_authenticated/account/'
    | '/me/_authenticated/appearance/'
    | '/me/_authenticated/notifications/'
    | '/me/_authenticated/profile/'
    | '/admin/_authenticated/blogs/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  BlogSitemapDotxmlRoute: typeof BlogSitemapDotxmlRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminRoute: typeof AdminRouteWithChildren
  MeRoute: typeof MeRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  publicVideoWallRoute: typeof publicVideoWallRoute
  publicVideoWallCinematicRoute: typeof publicVideoWallCinematicRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthReadyRoute: typeof AuthReadyRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  QuizQuizSlugRoute: typeof QuizQuizSlugRoute
  DesignSystemBadgesLazyRoute: typeof DesignSystemBadgesLazyRoute
  publicIndexRoute: typeof publicIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  publicLegalCookiesRoute: typeof publicLegalCookiesRoute
  publicLegalPrivacyRoute: typeof publicLegalPrivacyRoute
  publicLegalTermsRoute: typeof publicLegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-sitemap.xml': {
      id: '/blog-sitemap.xml'
      path: '/blog-sitemap.xml'
      fullPath: '/blog-sitemap.xml'
      preLoaderRoute: typeof BlogSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/badges': {
      id: '/design-system/badges'
      path: '/design-system/badges'
      fullPath: '/design-system/badges'
      preLoaderRoute: typeof DesignSystemBadgesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizSlug': {
      id: '/quiz/$quizSlug'
      path: '/quiz/$quizSlug'
      fullPath: '/quiz/$quizSlug'
      preLoaderRoute: typeof QuizQuizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/ready': {
      id: '/auth/ready'
      path: '/auth/ready'
      fullPath: '/auth/ready'
      preLoaderRoute: typeof AuthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/video-wall-cinematic': {
      id: '/(public)/video-wall-cinematic'
      path: '/video-wall-cinematic'
      fullPath: '/video-wall-cinematic'
      preLoaderRoute: typeof publicVideoWallCinematicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/video-wall': {
      id: '/(public)/video-wall'
      path: '/video-wall'
      fullPath: '/video-wall'
      preLoaderRoute: typeof publicVideoWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/_authenticated': {
      id: '/user/_authenticated'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserAuthenticatedRouteRouteImport
      parentRoute: typeof UserRoute
    }
    '/me/_authenticated': {
      id: '/me/_authenticated'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeAuthenticatedRouteRouteImport
      parentRoute: typeof MeRoute
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/_authenticated/': {
      id: '/user/_authenticated/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserAuthenticatedIndexRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
    '/me/_authenticated/': {
      id: '/me/_authenticated/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeAuthenticatedIndexRouteImport
      parentRoute: typeof MeAuthenticatedRouteRoute
    }
    '/docs/ux-guidelines/': {
      id: '/docs/ux-guidelines/'
      path: '/ux-guidelines'
      fullPath: '/docs/ux-guidelines'
      preLoaderRoute: typeof DocsUxGuidelinesIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/quiz-management': {
      id: '/admin/_authenticated/quiz-management'
      path: '/quiz-management'
      fullPath: '/admin/quiz-management'
      preLoaderRoute: typeof AdminAuthenticatedQuizManagementLazyRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/docs/ux-guidelines/overlays': {
      id: '/docs/ux-guidelines/overlays'
      path: '/ux-guidelines/overlays'
      fullPath: '/docs/ux-guidelines/overlays'
      preLoaderRoute: typeof DocsUxGuidelinesOverlaysRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/ux-guidelines/navigation': {
      id: '/docs/ux-guidelines/navigation'
      path: '/ux-guidelines/navigation'
      fullPath: '/docs/ux-guidelines/navigation'
      preLoaderRoute: typeof DocsUxGuidelinesNavigationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/ux-guidelines/layout-flows': {
      id: '/docs/ux-guidelines/layout-flows'
      path: '/ux-guidelines/layout-flows'
      fullPath: '/docs/ux-guidelines/layout-flows'
      preLoaderRoute: typeof DocsUxGuidelinesLayoutFlowsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/ux-guidelines/forms': {
      id: '/docs/ux-guidelines/forms'
      path: '/ux-guidelines/forms'
      fullPath: '/docs/ux-guidelines/forms'
      preLoaderRoute: typeof DocsUxGuidelinesFormsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/ux-guidelines/feedback': {
      id: '/docs/ux-guidelines/feedback'
      path: '/ux-guidelines/feedback'
      fullPath: '/docs/ux-guidelines/feedback'
      preLoaderRoute: typeof DocsUxGuidelinesFeedbackRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/ux-guidelines/accessibility': {
      id: '/docs/ux-guidelines/accessibility'
      path: '/ux-guidelines/accessibility'
      fullPath: '/docs/ux-guidelines/accessibility'
      preLoaderRoute: typeof DocsUxGuidelinesAccessibilityRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/(public)/legal/terms': {
      id: '/(public)/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof publicLegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/legal/privacy': {
      id: '/(public)/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof publicLegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/legal/cookies': {
      id: '/(public)/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof publicLegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/blogs': {
      id: '/admin/_authenticated/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminAuthenticatedBlogsRouteRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/me/_authenticated/profile/': {
      id: '/me/_authenticated/profile/'
      path: '/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeAuthenticatedProfileIndexRouteImport
      parentRoute: typeof MeAuthenticatedRouteRoute
    }
    '/me/_authenticated/notifications/': {
      id: '/me/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/me/notifications'
      preLoaderRoute: typeof MeAuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof MeAuthenticatedRouteRoute
    }
    '/me/_authenticated/appearance/': {
      id: '/me/_authenticated/appearance/'
      path: '/appearance'
      fullPath: '/me/appearance'
      preLoaderRoute: typeof MeAuthenticatedAppearanceIndexRouteImport
      parentRoute: typeof MeAuthenticatedRouteRoute
    }
    '/me/_authenticated/account/': {
      id: '/me/_authenticated/account/'
      path: '/account'
      fullPath: '/me/account'
      preLoaderRoute: typeof MeAuthenticatedAccountIndexRouteImport
      parentRoute: typeof MeAuthenticatedRouteRoute
    }
    '/admin/_authenticated/users/': {
      id: '/admin/_authenticated/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAuthenticatedUsersIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/tasks/': {
      id: '/admin/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminAuthenticatedTasksIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/quiz-analytics/': {
      id: '/admin/_authenticated/quiz-analytics/'
      path: '/quiz-analytics'
      fullPath: '/admin/quiz-analytics'
      preLoaderRoute: typeof AdminAuthenticatedQuizAnalyticsIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/kanban/': {
      id: '/admin/_authenticated/kanban/'
      path: '/kanban'
      fullPath: '/admin/kanban'
      preLoaderRoute: typeof AdminAuthenticatedKanbanIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/help-center/': {
      id: '/admin/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/admin/help-center'
      preLoaderRoute: typeof AdminAuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/chats/': {
      id: '/admin/_authenticated/chats/'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminAuthenticatedChatsIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/calendar/': {
      id: '/admin/_authenticated/calendar/'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminAuthenticatedCalendarIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/blogs/': {
      id: '/admin/_authenticated/blogs/'
      path: '/'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminAuthenticatedBlogsIndexRouteImport
      parentRoute: typeof AdminAuthenticatedBlogsRouteRoute
    }
    '/admin/_authenticated/apps/': {
      id: '/admin/_authenticated/apps/'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AdminAuthenticatedAppsIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/demos/three-pane-navigator': {
      id: '/admin/_authenticated/demos/three-pane-navigator'
      path: '/demos/three-pane-navigator'
      fullPath: '/admin/demos/three-pane-navigator'
      preLoaderRoute: typeof AdminAuthenticatedDemosThreePaneNavigatorLazyRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/blogs/new': {
      id: '/admin/_authenticated/blogs/new'
      path: '/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminAuthenticatedBlogsNewRouteImport
      parentRoute: typeof AdminAuthenticatedBlogsRouteRoute
    }
    '/admin/_authenticated/blogs/$id/edit': {
      id: '/admin/_authenticated/blogs/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/blogs/$id/edit'
      preLoaderRoute: typeof AdminAuthenticatedBlogsIdEditRouteImport
      parentRoute: typeof AdminAuthenticatedBlogsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsUxGuidelinesAccessibilityRoute: typeof DocsUxGuidelinesAccessibilityRoute
  DocsUxGuidelinesFeedbackRoute: typeof DocsUxGuidelinesFeedbackRoute
  DocsUxGuidelinesFormsRoute: typeof DocsUxGuidelinesFormsRoute
  DocsUxGuidelinesLayoutFlowsRoute: typeof DocsUxGuidelinesLayoutFlowsRoute
  DocsUxGuidelinesNavigationRoute: typeof DocsUxGuidelinesNavigationRoute
  DocsUxGuidelinesOverlaysRoute: typeof DocsUxGuidelinesOverlaysRoute
  DocsUxGuidelinesIndexRoute: typeof DocsUxGuidelinesIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsUxGuidelinesAccessibilityRoute: DocsUxGuidelinesAccessibilityRoute,
  DocsUxGuidelinesFeedbackRoute: DocsUxGuidelinesFeedbackRoute,
  DocsUxGuidelinesFormsRoute: DocsUxGuidelinesFormsRoute,
  DocsUxGuidelinesLayoutFlowsRoute: DocsUxGuidelinesLayoutFlowsRoute,
  DocsUxGuidelinesNavigationRoute: DocsUxGuidelinesNavigationRoute,
  DocsUxGuidelinesOverlaysRoute: DocsUxGuidelinesOverlaysRoute,
  DocsUxGuidelinesIndexRoute: DocsUxGuidelinesIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

interface AdminAuthenticatedBlogsRouteRouteChildren {
  AdminAuthenticatedBlogsNewRoute: typeof AdminAuthenticatedBlogsNewRoute
  AdminAuthenticatedBlogsIndexRoute: typeof AdminAuthenticatedBlogsIndexRoute
  AdminAuthenticatedBlogsIdEditRoute: typeof AdminAuthenticatedBlogsIdEditRoute
}

const AdminAuthenticatedBlogsRouteRouteChildren: AdminAuthenticatedBlogsRouteRouteChildren =
  {
    AdminAuthenticatedBlogsNewRoute: AdminAuthenticatedBlogsNewRoute,
    AdminAuthenticatedBlogsIndexRoute: AdminAuthenticatedBlogsIndexRoute,
    AdminAuthenticatedBlogsIdEditRoute: AdminAuthenticatedBlogsIdEditRoute,
  }

const AdminAuthenticatedBlogsRouteRouteWithChildren =
  AdminAuthenticatedBlogsRouteRoute._addFileChildren(
    AdminAuthenticatedBlogsRouteRouteChildren,
  )

interface AdminAuthenticatedRouteRouteChildren {
  AdminAuthenticatedBlogsRouteRoute: typeof AdminAuthenticatedBlogsRouteRouteWithChildren
  AdminAuthenticatedQuizManagementLazyRoute: typeof AdminAuthenticatedQuizManagementLazyRoute
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
  AdminAuthenticatedDemosThreePaneNavigatorLazyRoute: typeof AdminAuthenticatedDemosThreePaneNavigatorLazyRoute
  AdminAuthenticatedAppsIndexRoute: typeof AdminAuthenticatedAppsIndexRoute
  AdminAuthenticatedCalendarIndexRoute: typeof AdminAuthenticatedCalendarIndexRoute
  AdminAuthenticatedChatsIndexRoute: typeof AdminAuthenticatedChatsIndexRoute
  AdminAuthenticatedHelpCenterIndexRoute: typeof AdminAuthenticatedHelpCenterIndexRoute
  AdminAuthenticatedKanbanIndexRoute: typeof AdminAuthenticatedKanbanIndexRoute
  AdminAuthenticatedQuizAnalyticsIndexRoute: typeof AdminAuthenticatedQuizAnalyticsIndexRoute
  AdminAuthenticatedTasksIndexRoute: typeof AdminAuthenticatedTasksIndexRoute
  AdminAuthenticatedUsersIndexRoute: typeof AdminAuthenticatedUsersIndexRoute
}

const AdminAuthenticatedRouteRouteChildren: AdminAuthenticatedRouteRouteChildren =
  {
    AdminAuthenticatedBlogsRouteRoute:
      AdminAuthenticatedBlogsRouteRouteWithChildren,
    AdminAuthenticatedQuizManagementLazyRoute:
      AdminAuthenticatedQuizManagementLazyRoute,
    AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
    AdminAuthenticatedDemosThreePaneNavigatorLazyRoute:
      AdminAuthenticatedDemosThreePaneNavigatorLazyRoute,
    AdminAuthenticatedAppsIndexRoute: AdminAuthenticatedAppsIndexRoute,
    AdminAuthenticatedCalendarIndexRoute: AdminAuthenticatedCalendarIndexRoute,
    AdminAuthenticatedChatsIndexRoute: AdminAuthenticatedChatsIndexRoute,
    AdminAuthenticatedHelpCenterIndexRoute:
      AdminAuthenticatedHelpCenterIndexRoute,
    AdminAuthenticatedKanbanIndexRoute: AdminAuthenticatedKanbanIndexRoute,
    AdminAuthenticatedQuizAnalyticsIndexRoute:
      AdminAuthenticatedQuizAnalyticsIndexRoute,
    AdminAuthenticatedTasksIndexRoute: AdminAuthenticatedTasksIndexRoute,
    AdminAuthenticatedUsersIndexRoute: AdminAuthenticatedUsersIndexRoute,
  }

const AdminAuthenticatedRouteRouteWithChildren =
  AdminAuthenticatedRouteRoute._addFileChildren(
    AdminAuthenticatedRouteRouteChildren,
  )

interface AdminRouteChildren {
  AdminAuthenticatedRouteRoute: typeof AdminAuthenticatedRouteRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthenticatedRouteRoute: AdminAuthenticatedRouteRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MeAuthenticatedRouteRouteChildren {
  MeAuthenticatedIndexRoute: typeof MeAuthenticatedIndexRoute
  MeAuthenticatedAccountIndexRoute: typeof MeAuthenticatedAccountIndexRoute
  MeAuthenticatedAppearanceIndexRoute: typeof MeAuthenticatedAppearanceIndexRoute
  MeAuthenticatedNotificationsIndexRoute: typeof MeAuthenticatedNotificationsIndexRoute
  MeAuthenticatedProfileIndexRoute: typeof MeAuthenticatedProfileIndexRoute
}

const MeAuthenticatedRouteRouteChildren: MeAuthenticatedRouteRouteChildren = {
  MeAuthenticatedIndexRoute: MeAuthenticatedIndexRoute,
  MeAuthenticatedAccountIndexRoute: MeAuthenticatedAccountIndexRoute,
  MeAuthenticatedAppearanceIndexRoute: MeAuthenticatedAppearanceIndexRoute,
  MeAuthenticatedNotificationsIndexRoute:
    MeAuthenticatedNotificationsIndexRoute,
  MeAuthenticatedProfileIndexRoute: MeAuthenticatedProfileIndexRoute,
}

const MeAuthenticatedRouteRouteWithChildren =
  MeAuthenticatedRouteRoute._addFileChildren(MeAuthenticatedRouteRouteChildren)

interface MeRouteChildren {
  MeAuthenticatedRouteRoute: typeof MeAuthenticatedRouteRouteWithChildren
}

const MeRouteChildren: MeRouteChildren = {
  MeAuthenticatedRouteRoute: MeAuthenticatedRouteRouteWithChildren,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

interface UserAuthenticatedRouteRouteChildren {
  UserAuthenticatedIndexRoute: typeof UserAuthenticatedIndexRoute
}

const UserAuthenticatedRouteRouteChildren: UserAuthenticatedRouteRouteChildren =
  {
    UserAuthenticatedIndexRoute: UserAuthenticatedIndexRoute,
  }

const UserAuthenticatedRouteRouteWithChildren =
  UserAuthenticatedRouteRoute._addFileChildren(
    UserAuthenticatedRouteRouteChildren,
  )

interface UserRouteChildren {
  UserAuthenticatedRouteRoute: typeof UserAuthenticatedRouteRouteWithChildren
}

const UserRouteChildren: UserRouteChildren = {
  UserAuthenticatedRouteRoute: UserAuthenticatedRouteRouteWithChildren,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DocsRouteRoute: DocsRouteRouteWithChildren,
  BlogSitemapDotxmlRoute: BlogSitemapDotxmlRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminRoute: AdminRouteWithChildren,
  MeRoute: MeRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  publicVideoWallRoute: publicVideoWallRoute,
  publicVideoWallCinematicRoute: publicVideoWallCinematicRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthReadyRoute: AuthReadyRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  QuizQuizSlugRoute: QuizQuizSlugRoute,
  DesignSystemBadgesLazyRoute: DesignSystemBadgesLazyRoute,
  publicIndexRoute: publicIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  publicLegalCookiesRoute: publicLegalCookiesRoute,
  publicLegalPrivacyRoute: publicLegalPrivacyRoute,
  publicLegalTermsRoute: publicLegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
